#普通数据的配置
name: zhangsan
#对象的配置
person:
  name: hhhh
  age: 1888
  addr: oooooo
#行内对象配置
cat: {name: zhangsan,age: 18,addr: beijing}

#配置数组、集合(普通字符串)
city:
  - beijing
  - tianjing

#行内方式配置数组、集合（普通字符串）
cities: [beijing,tianjing,chongqing]


#配置数组、集合（对象）
students:
  - name: lisi
    age: 18
    addr: beijing
  - name: zhangsan
    age: 18
    addr: beijing


server:
  port: 8082

map:
  key1: value1
  key2: value2